program: sweeper.py
method: bayes
metric:
  name: loss
  goal: minimize
early_terminate:
  type: hyperband
  min_iter: 3
parameters:
  epochs:
    values: [100]
  batch_size:
    values: [8, 128]
  learning_rate:
    values: [0.001]
  optimizer:
    values: ["sgd"]
  scheduler:
    values: ['cos']
  use_feature_extract:
    values: [True]
  resnet_type:
    values: ['resnet18', 'resnet50']